// Package renderer generates human-readable projections of specs from SQLite state.
// Supported output formats: markdown, text, json.
package renderer

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mikesorae/speqlite/internal/db"
)

// Format defines the output format for rendered specs.
type Format string

const (
	FormatMarkdown Format = "markdown"
	FormatText     Format = "text"
	FormatJSON     Format = "json"
)

// ParseFormat converts a string to a Format, returning an error for unknown values.
func ParseFormat(s string) (Format, error) {
	switch strings.ToLower(s) {
	case "markdown", "md":
		return FormatMarkdown, nil
	case "text", "txt", "plain":
		return FormatText, nil
	case "json":
		return FormatJSON, nil
	default:
		return "", fmt.Errorf("renderer: unknown format %q; valid: markdown, text, json", s)
	}
}

// RenderSpec renders a single spec to the given format and returns the string.
func RenderSpec(s db.Spec, rels []db.Relation, format Format) (string, error) {
	switch format {
	case FormatMarkdown:
		return renderMarkdown(s, rels), nil
	case FormatText:
		return renderText(s, rels), nil
	case FormatJSON:
		return renderJSON(s, rels)
	default:
		return "", fmt.Errorf("renderer: unknown format %q", format)
	}
}

// WriteSpecFile renders a spec to a file at dir/<ID>.md (or .txt or .json).
// The directory must already exist.
func WriteSpecFile(s db.Spec, rels []db.Relation, dir string, format Format) (string, error) {
	content, err := RenderSpec(s, rels, format)
	if err != nil {
		return "", err
	}

	ext := formatExt(format)
	filename := filepath.Join(dir, s.ID+ext)

	tmp := filename + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("renderer: write tmp %q: %w", tmp, err)
	}
	if err := os.Rename(tmp, filename); err != nil {
		os.Remove(tmp)
		return "", fmt.Errorf("renderer: rename %q: %w", filename, err)
	}
	return filename, nil
}

// renderMarkdown produces a Markdown representation of a spec.
func renderMarkdown(s db.Spec, rels []db.Relation) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# %s\n\n", s.Title))
	sb.WriteString(fmt.Sprintf("**ID:** `%s`  \n", s.ID))
	sb.WriteString(fmt.Sprintf("**Kind:** %s  \n", s.Kind))
	sb.WriteString(fmt.Sprintf("**Status:** %s  \n", s.Status))
	sb.WriteString(fmt.Sprintf("**Version:** %d  \n", s.Version))
	sb.WriteString(fmt.Sprintf("**Updated:** %s  \n", s.UpdatedAt.UTC().Format(time.RFC3339)))
	sb.WriteString("\n")

	if s.Body != "" {
		sb.WriteString("## Description\n\n")
		sb.WriteString(s.Body)
		sb.WriteString("\n\n")
	}

	if len(rels) > 0 {
		sb.WriteString("## Relations\n\n")
		for _, r := range rels {
			sb.WriteString(fmt.Sprintf("- `%s` → **%s** → `%s`\n", r.FromID, r.Relation, r.ToID))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("---\n*Generated by speqlite at %s*\n", time.Now().UTC().Format(time.RFC3339)))
	return sb.String()
}

// renderText produces a plain-text representation of a spec.
func renderText(s db.Spec, rels []db.Relation) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("%s\n", s.Title))
	sb.WriteString(strings.Repeat("=", len(s.Title)))
	sb.WriteString("\n\n")

	sb.WriteString(fmt.Sprintf("ID:      %s\n", s.ID))
	sb.WriteString(fmt.Sprintf("Kind:    %s\n", s.Kind))
	sb.WriteString(fmt.Sprintf("Status:  %s\n", s.Status))
	sb.WriteString(fmt.Sprintf("Version: %d\n", s.Version))
	sb.WriteString(fmt.Sprintf("Updated: %s\n", s.UpdatedAt.UTC().Format(time.RFC3339)))

	if s.Body != "" {
		sb.WriteString("\nDescription:\n")
		sb.WriteString(s.Body)
		sb.WriteString("\n")
	}

	if len(rels) > 0 {
		sb.WriteString("\nRelations:\n")
		for _, r := range rels {
			sb.WriteString(fmt.Sprintf("  %s -[%s]-> %s\n", r.FromID, r.Relation, r.ToID))
		}
	}

	return sb.String()
}

// jsonSpec is the JSON-serialisable form of a rendered spec.
type jsonSpec struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Kind      string             `json:"kind"`
	Status    string             `json:"status"`
	Version   int                `json:"version"`
	Body      string             `json:"body"`
	Hash      string             `json:"hash"`
	CreatedAt string             `json:"created_at"`
	UpdatedAt string             `json:"updated_at"`
	Relations []jsonRelation     `json:"relations,omitempty"`
}

type jsonRelation struct {
	FromID   string `json:"from_id"`
	Relation string `json:"relation"`
	ToID     string `json:"to_id"`
}

// renderJSON produces a JSON representation of a spec.
func renderJSON(s db.Spec, rels []db.Relation) (string, error) {
	js := jsonSpec{
		ID:        s.ID,
		Title:     s.Title,
		Kind:      s.Kind,
		Status:    s.Status,
		Version:   s.Version,
		Body:      s.Body,
		Hash:      s.Hash,
		CreatedAt: s.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt: s.UpdatedAt.UTC().Format(time.RFC3339),
	}
	for _, r := range rels {
		js.Relations = append(js.Relations, jsonRelation{
			FromID:   r.FromID,
			Relation: r.Relation,
			ToID:     r.ToID,
		})
	}
	data, err := json.MarshalIndent(js, "", "  ")
	if err != nil {
		return "", fmt.Errorf("renderer: marshal json: %w", err)
	}
	return string(data), nil
}

// formatExt returns the file extension for a given format.
func formatExt(f Format) string {
	switch f {
	case FormatMarkdown:
		return ".md"
	case FormatText:
		return ".txt"
	case FormatJSON:
		return ".json"
	default:
		return ".md"
	}
}
